# Generated by Django 4.2.18 on 2025-01-26 13:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import psqlextra.manager.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotLogic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('sequence', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chatbotLogic.chatinfo')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
