# Generated by Django 5.1.4 on 2025-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotLogic', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinfo',
            name='new_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
