# Generated by Django 4.2.19 on 2025-02-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotLogic', '0003_otpregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_has_image',
            field=models.BooleanField(default=False),
        ),
    ]
